# Generated by Django 3.2.8 on 2022-01-11 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0008_auto_20220111_2106'),
        ('api_beer', '0004_migrate_beer_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'order_status',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_time', models.DateField()),
                ('total_price', models.FloatField()),
                ('total_discount', models.FloatField()),
                ('sum_price', models.FloatField()),
                ('shipping_address', models.CharField(max_length=50)),
                ('shipping_phone', models.CharField(max_length=20)),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api_beer.orderstatus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='api_account.user')),
            ],
            options={
                'db_table': 'order',
                'ordering': ('order_time',),
            },
        ),
    ]
