# Generated by Django 3.2.8 on 2022-01-11 17:10

from django.db import migrations


def initial_data(apps, schema_editor):
    order_status_model = apps.get_model("api_beer", "OrderStatus")

    order_status = [
        order_status_model(name="Pending"),
        order_status_model(name="Confirmed"),
        order_status_model(name="Delivering"),
        order_status_model(name="Delivered"),
        order_status_model(name="Completed"),
        order_status_model(name="Canceled"),
        order_status_model(name="Not Received")


    ]

    order_status_model.objects.bulk_create(order_status)


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0005_order_orderstatus'),
    ]

    operations = [
        migrations.RunPython(initial_data, migrations.RunPython.noop)
    ]
