# Generated by Django 3.2.8 on 2022-01-11 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0008_auto_20220111_2106'),
        ('api_beer', '0006_migrate_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='api_beer.beer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_detail', to='api_beer.order')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_time', models.DateField()),
                ('amount', models.IntegerField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api_beer.beer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='api_account.user')),
            ],
            options={
                'db_table': 'cart',
                'ordering': ('cart_time',),
            },
        ),
    ]
