# Generated by Django 3.2.8 on 2022-01-14 02:17

from django.db import migrations

from datetime import datetime, timedelta
from django.utils import timezone



def initial_data(apps, schema_editor):
    order_model = apps.get_model("api_beer", "Order")
    user_model = apps.get_model("api_account", "User")
    order_status_model = apps.get_model("api_beer", "OrderStatus")
    user = user_model.objects.all()
    date_time_now = timezone.localtime()
    completed_status = order_status_model.objects.get(name="COMPLETED")
    pending_status = order_status_model.objects.get(name="PENDING")
    delivering_status = order_status_model.objects.get(name="DELIVERING")
    delivered_status = order_status_model.objects.get(name="DELIVERED")
    confirmed_status = order_status_model.objects.get(name="CONFIRMED")
    canceled_status = order_status_model.objects.get(name="CANCELED")
    notreceivered_status = order_status_model.objects.get(name="NOT RECEIVED")

    order = [
        order_model(total_price=120000, total_discount=10000, sum_price=110000,
                    shipping_address="Hòa Thọ Đông, Cẩm Lệ, Đà Nẵng", shipping_phone="0359390202",
                    done_at=date_time_now - timedelta(days=19), order_status=completed_status, user=user[1]),
        order_model(total_price=150000, total_discount=20000, sum_price=130000,
                    shipping_address="757 Trần Cao Vân, Thanh Khê, Đà Nẵng", shipping_phone="0359390203",
                    done_at=date_time_now - timedelta(days=19), order_status=completed_status, user=user[1]),
        order_model(total_price=250000, total_discount=0, sum_price=250000,
                    shipping_address="108 Lê Độ, quận Thanh Khê, Tp. Đà Nẵng.", shipping_phone="0359390204",
                    order_status=pending_status, user=user[2]),
        order_model(total_price=120000, total_discount=0, sum_price=120000,
                    shipping_address="121 Cù Chính Lan, Thanh Khê, Đà Nẵng", shipping_phone="0359390205",
                    order_status=delivering_status, user=user[2]),
        order_model(total_price=400000, total_discount=50000, sum_price=350000,
                    shipping_address="152 Trần Cao Vân, Tam Thuận, Q. Thanh Khê, Đà Nẵng", shipping_phone="0359390206",
                    order_status=delivered_status, user=user[3]),
        order_model(total_price=320000, total_discount=20000, sum_price=300000,
                    shipping_address="111- 113, Trần Hưng Đạo, Quận Sơn Trà, ĐN", shipping_phone="0359390207",
                    order_status=confirmed_status, user=user[3]),
        order_model(total_price=350000, total_discount=10000, sum_price=340000,
                    shipping_address="61 Nguyễn Duy Hiệu, An Hải Đông, Sơn Trà, Đà Nẵng", shipping_phone="0359390208",
                    done_at=date_time_now - timedelta(days=19), order_status=completed_status, user=user[4]),
        order_model(total_price=250000, total_discount=0, sum_price=250000,
                    shipping_address="04 Hà Chương, Phường Phước Mỹ, Quận Sơn Trà, Tp.Đà Nẵng.",
                    shipping_phone="0359390209",
                    order_status=notreceivered_status, user=user[3]),
        order_model(total_price=180000, total_discount=10000, sum_price=170000,
                    shipping_address="8 Chu Huy Mân, Sơn Trà, Đà Nẵng Việt Nam", shipping_phone="0359390220",
                    order_status=canceled_status, user=user[4]),
        order_model(total_price=230000, total_discount=10000, sum_price=220000,
                    shipping_address="53 Phạm Cự Lượng, An Hải Bắc, Sơn Trà, Đà Nẵng", shipping_phone="0359390221",
                    order_status=canceled_status, user=user[5]),
                  

    ]

    order_model.objects.bulk_create(order)


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0007_migrate_order_status'),
    ]

    operations = [
        migrations.RunPython(initial_data, migrations.RunPython.noop)
    ]
