# Generated by Django 3.2.8 on 2022-01-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0009_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='done_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
