# Generated by Django 3.2.8 on 2022-01-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_beer', '0011_auto_20220119_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
