# Generated by Django 3.2.8 on 2022-01-14 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0008_auto_20220107_2219'),
        ('api_account', '0008_auto_20220111_2106'),
    ]

    operations = [
    ]
