# Generated by Django 3.2.8 on 2022-01-14 04:06
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.db import migrations
from api_account.constants import AccountData, UserData


def initial_data(apps, schema_editor):
    account_model = apps.get_model("api_account", "Account")
    user_model = apps.get_model("api_account", "User")
    role_model = apps.get_model("api_account", "Role")

    user_role = role_model.objects.filter(name="USER").first()
    accounts = []
    for account in AccountData.accounts:
        accounts.append(account_model(id=account['id'],
                                      first_name=account['first_name'], last_name=account['last_name'],
                                      is_staff=False,
                                      username=account['email'].split('@')[0],
                                      avatar=account.get('avatar',
                                                         'https://res.cloudinary.com/ddqzgiilu/image/upload/v1640923830/SGroup/KOB/abstract-user-flat-3_mk2mve.png'),
                                      email=account['email'],
                                      password=BaseUserManager().make_random_password(),
                                      role=user_role))

    account_model.objects.bulk_create(accounts)
    accounts = account_model.objects.all()
    users = []

    for i, user in enumerate(UserData.users):
        users.append(user_model(id=user['id'],
                                address=user['address'],
                                phone=user['phone'],
                                age=user['age'],
                                account=accounts[i]))

    user_model.objects.bulk_create(users)


class Migration(migrations.Migration):
    dependencies = [
        ('api_account', '0009_merge_0008_auto_20220107_2219_0008_auto_20220111_2106'),
    ]

    operations = [
        migrations.RunPython(initial_data, migrations.RunPython.noop)
    ]
